### PR TITLE
Added SVG background images and example slides

### PR DESCRIPTION
**Pull request by frankscholten**

### CODE REVIEW

**Comment by moretea** [comment]
What about adding this to the css in the theme?

https://github.com/ContainerSolutions/reveal-md/blob/master/resources/cs.css#L45

The selector `.reveal .slides > section` might work.

That would prevent you from having to copy&paste that every time again.

**Comment by frankscholten** [comment]
Nice, didn't know we could do that.

**Comment by frankscholten** [comment]
Tried adding `background-image` property but it was not picked up.

Opened an issue at https://github.com/webpro/reveal-md/issues/121

**Comment by frankscholten** [comment]
@moretea I have added the background image but when the title slide has its own background image they are both enabled.

**Pull request merged**
